name: net.Core Build with Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    # use ubuntu for more build minutes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore /WarnAsError --configuration Release
    - name: Test
      env:
        ImportantNumber: ${{ secrets.IMPORTANTNUMBER }}       
      run: dotnet test --no-restore --verbosity normal
